<% if fog_file = File.expand_path('~/.fog') and File.exists?(fog_file)
  fog_file = YAML.load_file(fog_file)
  ENV['AWS_ACCESS_KEY_ID'] ||= fog_file.fetch('travis-ci', {})['aws_access_key_id']
  ENV['AWS_SECRET_ACCESS_KEY'] ||= fog_file.fetch('travis-ci', {})['aws_secret_access_key']
  ENV['AWS_SSH_KEY_ID'] ||= fog_file.fetch('travis-ci', {})['aws_keypair_name']
  ENV['EC2_SSH_KEY_PATH'] ||= File.expand_path('~/.ssh/id_rsa_kitchen_ec2')
end %>
driver:
  require_chef_omnibus: "11.10.4"

provisioner:
  name: chef_solo
  attributes:
    test_kitchen: true
    newrelic:
      apikey: 'asdfasdfasdfasdfasdfasdf'
      policy_manager: 
        server_name: 'Test Server'
        startup_policy: 'App Servers'
        shutdown_policy: 'Decommissioned Servers'


platforms:
  - name: amazon-2015.09
    driver_plugin: ec2
    driver_config:
      shared_credentials_profile: travis-ci
      instance_type: c3.large
      image_id: ami-66b6c60c
      region: us-east-1
      availability_zone: us-east-1b
      security_group_ids: ['ci-testing']
      interface: public
      tags:
        Name: <%= "#{ENV['CI'] ? 'travis-ci' : ENV['USER']}-newrelic_policy_manager-kitchen" %>
        Env: public
    transport:
      ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>
      username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[newrelic_policy_manager::add_to_policy]
      - recipe[newrelic_policy_manager::remove_from_policy]
      - recipe[newrelic_policy_manager::delete_stopped]
    attributes:
